### ISSUE TITLE
What correct commant to flash firmware.bin?

### ISSUE THREAD

**Issue by lindrix** [ljk53/upytorch#19]
Hi.
I am have problems to flash the generated files of option D, because i build the clone code, how to the instrutions in Readme. But it does'nt have instrutions to flash the boot, partitions and firmware generated files.
I tried to flash with esptool in esp32 wroom 32 (4MB, 40MHz), using the default addresses to memory (to 0x8000 to partitions.bin and 0x10000 to firmware).
After this, the process boot doesn't complet, with error of partition table corrupted.
Already i try build files with branch fix, beyound main, and this doesn't work. Also i try flash only the firmware file, but equal...
Because i ask to for you for command correct to flash files, for done the process, part of the research i'm development about this.
Thank you for attenttion.

**Comment by ljk53** [comment]
I think I used this command:
```
esptool.py --chip esp32 write_flash -z 0x1000 build/firmware.bin
```
You may want to try erasing the flash first:
```
esptool.py --chip esp32 erase_flash
```
The esp32 I tested has 16M flash (m5stack core), so the partition table needs to be updated for your case I think.

**Comment by lindrix** [comment]
I understand, and i go to try so.
Thank you!

**Comment by adrian70000** [comment]
Hi, I also have the model with 4MB flash. What would I need to do to update the partition table and make it boot? I was also using option D.

edit: I made it work. Changing partition table is really well explained [here.](https://stackoverflow.com/a/69277852) You can skip to the part where it says "Default partitions.csv file contents", you don't need to do any of the steps before. I also attached my .csv partition table for 4MB esp32. After that you just convert it to .bin format using:

`python gen_esp32part.py input_partitions.csv binary_partitions.bin` 

You can get that .py file from [here](https://github.com/espressif/esp-idf/blob/45c1d1cba2/components/partition_table/gen_esp32part.py).

Delete the firmware.bin that was made before and run the last command from option D again.

[input_partitions.csv](https://github.com/ljk53/upytorch/files/8550283/input_partitions.csv)
.
